### ISSUE TITLE
[SNAPSHOT] Basic MNIST model fails in snapshot

### ISSUE THREAD

**Issue by rnett** [deeplearning4j/deeplearning4j#7349]
#### Issue Description

Basic 2 conv, 2 pooling, dense model for MNIST fails, but only in the snapshot build.  It classifies everything as 0s (it works just fine in beta3).

When comparing the `GraphConfig.toYaml()`s, the only things that stick out to me is that `pretrain` on each layer is missing (is false in beta3), `backprop` on the graph is missing (is true in beta3, backpropType is still the same), and `gainInit` is 1 on the shapshot.  Also, the layer regularizes are set to empty lists in the shapshot instead of not present (in beta3).

I would compare the model summaries but this throws a NPE in the snapshot build (I'm making another issue for that).

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-SNAPSHOT
* platform information (OS, etc): Windows 64bit
* CUDA version, if used: 10.0
* NVIDIA driver version, if in use: 411.31

Model (using custom wrappers):
```kotlin
optimizer = Updater.SGD.iUpdaterWithDefaultConfig

input("image", 784)

+ReshapeVertex(1, 28, 28)

+Convolution2DLayer(20, kernelSize = P(5, 5)){ activation = ActivationReLU() }
+Subsampling2DLayer(kernelSize = P(2, 2), stride = P(2, 2))

+Convolution2DLayer(20, kernelSize = P(5, 5)){ activation = ActivationReLU() }
+Subsampling2DLayer(kernelSize = P(2, 2), stride = P(2, 2))

+FlattenVertex()
+DenseLayer(200) { activation = ActivationReLU() }

!+OutputLayer(10, loss = LossNegativeLogLikelihood()){
    activation = ActivationSoftmax()
}
```

**Comment by rnett** [comment]
## Exported configs
### Beta3
```yaml
backprop: true
backpropType: "Standard"
cacheMode: "NONE"
defaultConfiguration:
  cacheMode: "NONE"
  epochCount: 0
  iterationCount: 0
  layer: null
  maxNumLineSearchIterations: 5
  miniBatch: true
  minimize: true
  optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
  pretrain: false
  seed: 1553546109284
  stepFunction: null
  variables: []
epochCount: 0
inferenceWorkspaceMode: "ENABLED"
iterationCount: 0
legacyBatchScaledL2: false
networkInputs:
- "image"
networkOutputs:
- "output"
pretrain: false
tbpttBackLength: 20
tbpttFwdLength: 20
topologicalOrder: null
topologicalOrderStr: null
trainingWorkspaceMode: "ENABLED"
vertexInputs:
  reshape_0:
  - "image"
  conv2d:
  - "reshape_0"
  subsampling2d:
  - "conv2d"
  conv2d_1:
  - "subsampling2d"
  subsampling2d_1:
  - "conv2d_1"
  reshape_1:
  - "subsampling2d_1"
  dense:
  - "reshape_1"
  output:
  - "dense"
vertices:
  reshape_0: !<org.deeplearning4j.nn.conf.graph.ReshapeVertex>
    maskShape: null
    newShape:
    - -1
    - 1
    - 28
    - 28
    reshapeOrder: "c"
  conv2d: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.ConvolutionLayer>
        activationFn: !<org.nd4j.linalg.activations.impl.ActivationReLU> {}
        biasInit: 0.0
        biasUpdater: null
        constraints: null
        convolutionMode: "Truncate"
        cudnnAlgoMode: "PREFER_FASTEST"
        cudnnAllowFallback: true
        cudnnBwdDataAlgo: null
        cudnnBwdFilterAlgo: null
        cudnnFwdAlgo: null
        dilation:
        - 1
        - 1
        dist: null
        gradientNormalization: "None"
        gradientNormalizationThreshold: 1.0
        hasBias: true
        idropout: null
        iupdater: !<org.nd4j.linalg.learning.config.Sgd>
          learningRate: 0.001
        kernelSize:
        - 5
        - 5
        l1: 0.0
        l1Bias: 0.0
        l2: 0.0
        l2Bias: 0.0
        layerName: "conv2d"
        nin: 1
        nout: 20
        padding:
        - 0
        - 0
        pretrain: false
        stride:
        - 1
        - 1
        weightInit: "XAVIER"
        weightNoise: null
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      pretrain: false
      seed: 1553546109284
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
  subsampling2d: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.SubsamplingLayer>
        constraints: null
        convolutionMode: "Truncate"
        cudnnAllowFallback: true
        dilation:
        - 1
        - 1
        eps: 1.0E-8
        gradientNormalization: "None"
        gradientNormalizationThreshold: 0.0
        idropout: null
        kernelSize:
        - 2
        - 2
        layerName: "subsampling2d"
        padding:
        - 0
        - 0
        pnorm: 0
        poolingType: "MAX"
        pretrain: false
        stride:
        - 2
        - 2
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      pretrain: false
      seed: 1553546109284
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
  conv2d_1: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.ConvolutionLayer>
        activationFn: !<org.nd4j.linalg.activations.impl.ActivationReLU> {}
        biasInit: 0.0
        biasUpdater: null
        constraints: null
        convolutionMode: "Truncate"
        cudnnAlgoMode: "PREFER_FASTEST"
        cudnnAllowFallback: true
        cudnnBwdDataAlgo: null
        cudnnBwdFilterAlgo: null
        cudnnFwdAlgo: null
        dilation:
        - 1
        - 1
        dist: null
        gradientNormalization: "None"
        gradientNormalizationThreshold: 1.0
        hasBias: true
        idropout: null
        iupdater: !<org.nd4j.linalg.learning.config.Sgd>
          learningRate: 0.001
        kernelSize:
        - 5
        - 5
        l1: 0.0
        l1Bias: 0.0
        l2: 0.0
        l2Bias: 0.0
        layerName: "conv2d_1"
        nin: 20
        nout: 20
        padding:
        - 0
        - 0
        pretrain: false
        stride:
        - 1
        - 1
        weightInit: "XAVIER"
        weightNoise: null
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      pretrain: false
      seed: 1553546109284
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
  subsampling2d_1: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.SubsamplingLayer>
        constraints: null
        convolutionMode: "Truncate"
        cudnnAllowFallback: true
        dilation:
        - 1
        - 1
        eps: 1.0E-8
        gradientNormalization: "None"
        gradientNormalizationThreshold: 0.0
        idropout: null
        kernelSize:
        - 2
        - 2
        layerName: "subsampling2d_1"
        padding:
        - 0
        - 0
        pnorm: 0
        poolingType: "MAX"
        pretrain: false
        stride:
        - 2
        - 2
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      pretrain: false
      seed: 1553546109284
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
  reshape_1: !<org.deeplearning4j.nn.conf.graph.ReshapeVertex>
    maskShape: null
    newShape:
    - -1
    - 320
    reshapeOrder: "c"
  dense: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.DenseLayer>
        activationFn: !<org.nd4j.linalg.activations.impl.ActivationReLU> {}
        biasInit: 0.0
        biasUpdater: null
        constraints: null
        dist: null
        gradientNormalization: "None"
        gradientNormalizationThreshold: 1.0
        hasBias: true
        idropout: null
        iupdater: !<org.nd4j.linalg.learning.config.Sgd>
          learningRate: 0.001
        l1: 0.0
        l1Bias: 0.0
        l2: 0.0
        l2Bias: 0.0
        layerName: "dense"
        nin: 320
        nout: 200
        pretrain: false
        weightInit: "XAVIER"
        weightNoise: null
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      pretrain: false
      seed: 1553546109284
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
  output: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.OutputLayer>
        activationFn: !<org.nd4j.linalg.activations.impl.ActivationSoftmax> {}
        biasInit: 0.0
        biasUpdater: null
        constraints: null
        dist: null
        gradientNormalization: "None"
        gradientNormalizationThreshold: 1.0
        hasBias: true
        idropout: null
        iupdater: !<org.nd4j.linalg.learning.config.Sgd>
          learningRate: 0.001
        l1: 0.0
        l1Bias: 0.0
        l2: 0.0
        l2Bias: 0.0
        layerName: "output"
        legacyBatchScaledL2: false
        lossFn: !<org.nd4j.linalg.lossfunctions.impl.LossNegativeLogLikelihood>
          configProperties: false
          numOutputs: -1
          softmaxClipEps: 1.0E-10
        nin: 200
        nout: 10
        pretrain: false
        weightInit: "XAVIER"
        weightNoise: null
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      pretrain: false
      seed: 1553546109284
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
```
### Snapshot
```yaml
backpropType: "Standard"
cacheMode: "NONE"
defaultConfiguration:
  cacheMode: "NONE"
  epochCount: 0
  iterationCount: 0
  layer: null
  maxNumLineSearchIterations: 5
  miniBatch: true
  minimize: true
  optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
  seed: 1553546157638
  stepFunction: null
  variables: []
epochCount: 0
inferenceWorkspaceMode: "ENABLED"
iterationCount: 0
networkInputs:
- "image"
networkOutputs:
- "output"
tbpttBackLength: 20
tbpttFwdLength: 20
topologicalOrder: null
topologicalOrderStr: null
trainingWorkspaceMode: "ENABLED"
validateOutputLayerConfig: true
vertexInputs:
  reshape_0:
  - "image"
  conv2d:
  - "reshape_0"
  subsampling2d:
  - "conv2d"
  conv2d_1:
  - "subsampling2d"
  subsampling2d_1:
  - "conv2d_1"
  reshape_1:
  - "subsampling2d_1"
  dense:
  - "reshape_1"
  output:
  - "dense"
vertices:
  reshape_0: !<org.deeplearning4j.nn.conf.graph.ReshapeVertex>
    maskShape: null
    newShape:
    - -1
    - 1
    - 28
    - 28
    reshapeOrder: "c"
  conv2d: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.ConvolutionLayer>
        activationFn: !<org.nd4j.linalg.activations.impl.ActivationReLU> {}
        biasInit: 0.0
        biasUpdater: null
        constraints: null
        convolutionMode: "Truncate"
        cudnnAlgoMode: "PREFER_FASTEST"
        cudnnAllowFallback: true
        cudnnBwdDataAlgo: null
        cudnnBwdFilterAlgo: null
        cudnnFwdAlgo: null
        dilation:
        - 1
        - 1
        gainInit: 1.0
        gradientNormalization: "None"
        gradientNormalizationThreshold: 1.0
        hasBias: true
        idropout: null
        iupdater: !<org.nd4j.linalg.learning.config.Sgd>
          learningRate: 0.001
        kernelSize:
        - 5
        - 5
        layerName: "conv2d"
        nin: 1
        nout: 20
        padding:
        - 0
        - 0
        regularization: []
        regularizationBias: []
        stride:
        - 1
        - 1
        weightInitFn: !<org.deeplearning4j.nn.weights.WeightInitXavier> {}
        weightNoise: null
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      seed: 1553546157638
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
  subsampling2d: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.SubsamplingLayer>
        constraints: null
        convolutionMode: "Truncate"
        cudnnAllowFallback: true
        dilation:
        - 1
        - 1
        eps: 1.0E-8
        gradientNormalization: "None"
        gradientNormalizationThreshold: 0.0
        idropout: null
        kernelSize:
        - 2
        - 2
        layerName: "subsampling2d"
        padding:
        - 0
        - 0
        pnorm: 0
        poolingType: "MAX"
        stride:
        - 2
        - 2
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      seed: 1553546157638
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
  conv2d_1: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.ConvolutionLayer>
        activationFn: !<org.nd4j.linalg.activations.impl.ActivationReLU> {}
        biasInit: 0.0
        biasUpdater: null
        constraints: null
        convolutionMode: "Truncate"
        cudnnAlgoMode: "PREFER_FASTEST"
        cudnnAllowFallback: true
        cudnnBwdDataAlgo: null
        cudnnBwdFilterAlgo: null
        cudnnFwdAlgo: null
        dilation:
        - 1
        - 1
        gainInit: 1.0
        gradientNormalization: "None"
        gradientNormalizationThreshold: 1.0
        hasBias: true
        idropout: null
        iupdater: !<org.nd4j.linalg.learning.config.Sgd>
          learningRate: 0.001
        kernelSize:
        - 5
        - 5
        layerName: "conv2d_1"
        nin: 20
        nout: 20
        padding:
        - 0
        - 0
        regularization: []
        regularizationBias: []
        stride:
        - 1
        - 1
        weightInitFn: !<org.deeplearning4j.nn.weights.WeightInitXavier> {}
        weightNoise: null
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      seed: 1553546157638
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
  subsampling2d_1: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.SubsamplingLayer>
        constraints: null
        convolutionMode: "Truncate"
        cudnnAllowFallback: true
        dilation:
        - 1
        - 1
        eps: 1.0E-8
        gradientNormalization: "None"
        gradientNormalizationThreshold: 0.0
        idropout: null
        kernelSize:
        - 2
        - 2
        layerName: "subsampling2d_1"
        padding:
        - 0
        - 0
        pnorm: 0
        poolingType: "MAX"
        stride:
        - 2
        - 2
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      seed: 1553546157638
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
  reshape_1: !<org.deeplearning4j.nn.conf.graph.ReshapeVertex>
    maskShape: null
    newShape:
    - -1
    - 320
    reshapeOrder: "c"
  dense: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.DenseLayer>
        activationFn: !<org.nd4j.linalg.activations.impl.ActivationReLU> {}
        biasInit: 0.0
        biasUpdater: null
        constraints: null
        gainInit: 1.0
        gradientNormalization: "None"
        gradientNormalizationThreshold: 1.0
        hasBias: true
        hasLayerNorm: false
        idropout: null
        iupdater: !<org.nd4j.linalg.learning.config.Sgd>
          learningRate: 0.001
        layerName: "dense"
        nin: 320
        nout: 200
        regularization: []
        regularizationBias: []
        weightInitFn: !<org.deeplearning4j.nn.weights.WeightInitXavier> {}
        weightNoise: null
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      seed: 1553546157638
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
  output: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.OutputLayer>
        activationFn: !<org.nd4j.linalg.activations.impl.ActivationSoftmax> {}
        biasInit: 0.0
        biasUpdater: null
        constraints: null
        gainInit: 1.0
        gradientNormalization: "None"
        gradientNormalizationThreshold: 1.0
        hasBias: true
        idropout: null
        iupdater: !<org.nd4j.linalg.learning.config.Sgd>
          learningRate: 0.001
        layerName: "output"
        lossFn: !<org.nd4j.linalg.lossfunctions.impl.LossNegativeLogLikelihood>
          configProperties: false
          numOutputs: -1
          softmaxClipEps: 1.0E-10
        nin: 200
        nout: 10
        regularization: []
        regularizationBias: []
        weightInitFn: !<org.deeplearning4j.nn.weights.WeightInitXavier> {}
        weightNoise: null
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      seed: 1553546157638
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
```
