### ISSUE TITLE
ComputationGraph summary method throws NPE if used before training

### ISSUE THREAD

**Issue by rnett** [deeplearning4j/deeplearning4j#7350]
#### Issue Description

Calling the `summary()` method on a `ComputationGraph` object throws a NPE.

```java
java.lang.NullPointerException
	at org.deeplearning4j.nn.graph.ComputationGraph.summary(ComputationGraph.java:4189)
	at org.deeplearning4j.nn.graph.ComputationGraph.summary(ComputationGraph.java:4155)
	at com.rnett.knn.layers.ConvTests.test mnist(Convlution.kt:69)
```

The statement in question is:
```java
for (int currVertexIdx : topologicalOrder){
```

`topologicalOrder` is null here, which causes the NPE.

Note that `summary()` is the first call after building the graph.

**Update:**  The issue appears to be that `ComputationGraph.topologicalOrder` is set in the `init` method, so if you call `summary()` before training, you get the NPE.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta3 (issue is still there in SNAPSHOT)
* platform information (OS, etc): Windows 64bit
* CUDA version, if used: 10.0
* NVIDIA driver version, if in use: 411.31

**Comment by rnett** [comment]
## Exported config
```yaml
backprop: true
backpropType: "Standard"
cacheMode: "NONE"
defaultConfiguration:
  cacheMode: "NONE"
  epochCount: 0
  iterationCount: 0
  layer: null
  maxNumLineSearchIterations: 5
  miniBatch: true
  minimize: true
  optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
  pretrain: false
  seed: 1553546109284
  stepFunction: null
  variables: []
epochCount: 0
inferenceWorkspaceMode: "ENABLED"
iterationCount: 0
legacyBatchScaledL2: false
networkInputs:
- "image"
networkOutputs:
- "output"
pretrain: false
tbpttBackLength: 20
tbpttFwdLength: 20
topologicalOrder: null
topologicalOrderStr: null
trainingWorkspaceMode: "ENABLED"
vertexInputs:
  reshape_0:
  - "image"
  conv2d:
  - "reshape_0"
  subsampling2d:
  - "conv2d"
  conv2d_1:
  - "subsampling2d"
  subsampling2d_1:
  - "conv2d_1"
  reshape_1:
  - "subsampling2d_1"
  dense:
  - "reshape_1"
  output:
  - "dense"
vertices:
  reshape_0: !<org.deeplearning4j.nn.conf.graph.ReshapeVertex>
    maskShape: null
    newShape:
    - -1
    - 1
    - 28
    - 28
    reshapeOrder: "c"
  conv2d: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.ConvolutionLayer>
        activationFn: !<org.nd4j.linalg.activations.impl.ActivationReLU> {}
        biasInit: 0.0
        biasUpdater: null
        constraints: null
        convolutionMode: "Truncate"
        cudnnAlgoMode: "PREFER_FASTEST"
        cudnnAllowFallback: true
        cudnnBwdDataAlgo: null
        cudnnBwdFilterAlgo: null
        cudnnFwdAlgo: null
        dilation:
        - 1
        - 1
        dist: null
        gradientNormalization: "None"
        gradientNormalizationThreshold: 1.0
        hasBias: true
        idropout: null
        iupdater: !<org.nd4j.linalg.learning.config.Sgd>
          learningRate: 0.001
        kernelSize:
        - 5
        - 5
        l1: 0.0
        l1Bias: 0.0
        l2: 0.0
        l2Bias: 0.0
        layerName: "conv2d"
        nin: 1
        nout: 20
        padding:
        - 0
        - 0
        pretrain: false
        stride:
        - 1
        - 1
        weightInit: "XAVIER"
        weightNoise: null
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      pretrain: false
      seed: 1553546109284
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
  subsampling2d: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.SubsamplingLayer>
        constraints: null
        convolutionMode: "Truncate"
        cudnnAllowFallback: true
        dilation:
        - 1
        - 1
        eps: 1.0E-8
        gradientNormalization: "None"
        gradientNormalizationThreshold: 0.0
        idropout: null
        kernelSize:
        - 2
        - 2
        layerName: "subsampling2d"
        padding:
        - 0
        - 0
        pnorm: 0
        poolingType: "MAX"
        pretrain: false
        stride:
        - 2
        - 2
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      pretrain: false
      seed: 1553546109284
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
  conv2d_1: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.ConvolutionLayer>
        activationFn: !<org.nd4j.linalg.activations.impl.ActivationReLU> {}
        biasInit: 0.0
        biasUpdater: null
        constraints: null
        convolutionMode: "Truncate"
        cudnnAlgoMode: "PREFER_FASTEST"
        cudnnAllowFallback: true
        cudnnBwdDataAlgo: null
        cudnnBwdFilterAlgo: null
        cudnnFwdAlgo: null
        dilation:
        - 1
        - 1
        dist: null
        gradientNormalization: "None"
        gradientNormalizationThreshold: 1.0
        hasBias: true
        idropout: null
        iupdater: !<org.nd4j.linalg.learning.config.Sgd>
          learningRate: 0.001
        kernelSize:
        - 5
        - 5
        l1: 0.0
        l1Bias: 0.0
        l2: 0.0
        l2Bias: 0.0
        layerName: "conv2d_1"
        nin: 20
        nout: 20
        padding:
        - 0
        - 0
        pretrain: false
        stride:
        - 1
        - 1
        weightInit: "XAVIER"
        weightNoise: null
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      pretrain: false
      seed: 1553546109284
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
  subsampling2d_1: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.SubsamplingLayer>
        constraints: null
        convolutionMode: "Truncate"
        cudnnAllowFallback: true
        dilation:
        - 1
        - 1
        eps: 1.0E-8
        gradientNormalization: "None"
        gradientNormalizationThreshold: 0.0
        idropout: null
        kernelSize:
        - 2
        - 2
        layerName: "subsampling2d_1"
        padding:
        - 0
        - 0
        pnorm: 0
        poolingType: "MAX"
        pretrain: false
        stride:
        - 2
        - 2
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      pretrain: false
      seed: 1553546109284
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
  reshape_1: !<org.deeplearning4j.nn.conf.graph.ReshapeVertex>
    maskShape: null
    newShape:
    - -1
    - 320
    reshapeOrder: "c"
  dense: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.DenseLayer>
        activationFn: !<org.nd4j.linalg.activations.impl.ActivationReLU> {}
        biasInit: 0.0
        biasUpdater: null
        constraints: null
        dist: null
        gradientNormalization: "None"
        gradientNormalizationThreshold: 1.0
        hasBias: true
        idropout: null
        iupdater: !<org.nd4j.linalg.learning.config.Sgd>
          learningRate: 0.001
        l1: 0.0
        l1Bias: 0.0
        l2: 0.0
        l2Bias: 0.0
        layerName: "dense"
        nin: 320
        nout: 200
        pretrain: false
        weightInit: "XAVIER"
        weightNoise: null
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      pretrain: false
      seed: 1553546109284
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
  output: !<org.deeplearning4j.nn.conf.graph.LayerVertex>
    layerConf:
      cacheMode: "NONE"
      epochCount: 0
      iterationCount: 0
      layer: !<org.deeplearning4j.nn.conf.layers.OutputLayer>
        activationFn: !<org.nd4j.linalg.activations.impl.ActivationSoftmax> {}
        biasInit: 0.0
        biasUpdater: null
        constraints: null
        dist: null
        gradientNormalization: "None"
        gradientNormalizationThreshold: 1.0
        hasBias: true
        idropout: null
        iupdater: !<org.nd4j.linalg.learning.config.Sgd>
          learningRate: 0.001
        l1: 0.0
        l1Bias: 0.0
        l2: 0.0
        l2Bias: 0.0
        layerName: "output"
        legacyBatchScaledL2: false
        lossFn: !<org.nd4j.linalg.lossfunctions.impl.LossNegativeLogLikelihood>
          configProperties: false
          numOutputs: -1
          softmaxClipEps: 1.0E-10
        nin: 200
        nout: 10
        pretrain: false
        weightInit: "XAVIER"
        weightNoise: null
      maxNumLineSearchIterations: 5
      miniBatch: true
      minimize: true
      optimizationAlgo: "STOCHASTIC_GRADIENT_DESCENT"
      pretrain: false
      seed: 1553546109284
      stepFunction: null
      variables: []
    outputVertex: false
    preProcessor: null
```
